language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nayl0r88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nayl0r88/docker-react npm run test -- --coverage
